module.exports = {
    All: 0,
    STANDARD: 1,
    CAN_DRIVE_CHILDREN: 2,
    HELP_GETTING_OUT: 3,
    MEDICAL: 4,
    FOLDING_WHEELCHAIR: 5,
    ELECTRIC_WHEELCHAIR: 6,
    ADVANCED_MEDICAL_NEEDS: 7
};