
module.exports = {
    PHONE_REGEX: /^\+[1-9]\d{1,14}$/,
    VERIFICATION_CODE_LENGTH: 4,
    VERIFICATION_CODE_REGEX: /^\d*$/,
    MIN_PASSWORD_LENGTH: 8,
    MAX_PASSWORD_LENGTH: 40,
    MIN_ADDRESS_LENGTH: 1,
    MAX_ADDRESS_LENGTH: 50,
    MIN_CITY_LENGTH: 1,
    MAX_CITY_LENGTH: 30,
    MIN_MODEL_LENGTH: 1,
    MAX_MODEL_LENGTH: 30,
    MIN_LICENCE_PLATE_LENGTH: 1,
    MAX_LICENCE_PLATE_LENGTH: 8,
    MIN_NUM_OF_SEATS: 1,
    MAX_NUM_OF_SEATS: 10,
    MIN_ADMIN_PASSWORD_LENGTH: 6,
    MAX_ADMIN_PASSWORD_LENGTH: 16,
    MIN_NAME_LENGTH: 1,
    MAX_NAME_LENGTH: 30,
    MAX_EMAIL_LENGTH: 129,
    MIN_CANCELLATION_FEE: 50,
    MAX_COMMENT_LENGTH: 100,
    MIN_RATE: 1,
    MAX_RATE: 5,
    MAX_COMMENT: 500,

    MODEL_REGEX: /^[A-Z0-9a-z\s-]+$/,
    LICENCE_PLATE_REGEX: /^[A-Z0-9]+$/,
    USER_NAME_REGEX: /^[A-Z][A-Za-z\s-]*$/,
    PASSWORD_BASE_REGEX: /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d).+$/,
    PASSWORD_LENGTH: /^.{8,40}$/,
    PASSWORD_SPACE_ONLY_REGEX: /^\S+$/,

    MAX_PHOTO_SIZE: 8 * 1024 * 1024, //8Mb
    PHOTO_MIME_TYPES: [
        'image/jpeg',
        'image/png'
    ]
};